import { Partners } from './components/Partners/index'

export { Admission } from './components/Admission'
export { CardList } from './components/CardList'
export { CareerOpportunities } from './components/CareerOpportunities'
export { Hero } from './components/Hero'
export { TextAndVideo1 } from './components/TextAndVideo1'
export { TextAndVideo2 } from './components/TextAndVideo2'
export { EquipmentGallery } from './components/EquipmentGallery'
export { Footer } from './components/Footer'
export { InfoVideo } from './components/InfoVideo'
export { JobsFuture } from './components/JobsFuture'
export { Partners } from './components/Partners'
export { Questions } from './components/Questions'
